export const basicWidgetSettings = {
  selectedSettings: null,
  device: 0,
  position: null,
  selectedTemplate: null,
  layout: {
    columns: 4,
    rows: 2,
    padding: 0,
    borderRadius: 0,
    mobileColumns: 2,
    mobileRows: 4,
    backgroundColor: '#FFFFFF',
  },
  heading: {
    radio: ['basic'],
    enableTitle: false,
    enableDescription: false,
    enableButton: false,
  },
  items: {
    enableHover: false,
    backgroundColor: '#000000',
    opacity: 60,
    color: '#FFFFFF',
    textAlign: 'center',
    textSize: 15,
    textWeight: 500,
    caption: false,
  },
  popup: {
    profile: false,
    profileTab: 'same',
    folowBtn: false,
    folowBtnText: 'Follow',
    caption: false,
    date: false,
    instaView: false,
    instaViewTab: 'same',
  },
  shoppable: {
    showIcon: false,
    hotSpotColor: '#dddddd',
    hotSpotHover: '#000',
    opacity: 90,
    hotspotLink: 'new',
    displayProduct: 'column',
    ctaBtn: 'same',
    ctaBtnText: 'View details',
    ctaBtnColor: '#000000',
    ctaBtnTextColor: '#FFFFFF',
  },
}
